# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'First_Try.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from typing import Text
from PyQt5 import QtCore, QtGui, QtWidgets
before_first_num1 = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n""<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n""p, li { white-space: pre-wrap; }\n""</style></head><body"
new_process = " bgcolor=\"#00acff\" "
hole = " bgcolor=\"#FA669A\" "
old_process = " bgcolor=\"#e3f55a\" "
color = " bgcolor=\"#e3f55a\" "
before_first_num2 = " style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n""<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">"
before_name = "</span></p>\n""<p style=\" margin-top:13px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">              "
far_before_last_num = "</span></p>\n""<p style=\" margin-top:"

before_last_num= "px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">"
ending = "</span></p></body></html>"


class Ui_ChartWindow(object):
    def setupUi(self, ChartWindow,myList):
        ChartWindow.setObjectName("ChartWindow")
        ChartWindow.resize(450, 750)
        ChartWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(ChartWindow)
        self.centralwidget.setObjectName("centralwidget")
        ##############
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(110, 50, 221, 500))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 198, 50))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        ###############)
        start = 50
        for i in range(0,len(myList)):
            text = str(i)
            self.text = QtWidgets.QTextBrowser(self.centralwidget)
            length = myList[i]['end'] - myList[i]['start']
            self.text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
            self.text.setObjectName(text)
            self.verticalLayout_2.addWidget(self.text)
            start += length
            ChartWindow.setCentralWidget(self.centralwidget)
            if myList[i]['name'][0] == 'P' or myList[i]['name'][0] == 'P' :
                color = new_process
            elif myList[i]['name'][0] == 'H' or myList[i]['name'][0] == 'h' :
                color = hole
            else:
                color = old_process
            self.retranslateUi(ChartWindow,text,i,length,myList,color)
            QtCore.QTimer.singleShot(0, self.scrollAreaWidgetContents_2.adjustSize)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        ChartWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChartWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        ChartWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChartWindow)
        self.statusbar.setObjectName("statusbar")
        ChartWindow.setStatusBar(self.statusbar)

        self.retranslateUii(ChartWindow)
        QtCore.QMetaObject.connectSlotsByName(ChartWindow)

    def retranslateUi(self, ChartWindow,text,i,length,myList,color):
        _translate = QtCore.QCoreApplication.translate
        ChartWindow.setWindowTitle(_translate("ChartWindow", "ChartWindow"))    
        self.text.setHtml(_translate("ChartWindow", before_first_num1+color+before_first_num2+str(myList[i]['start'])+before_name+myList[i]['name']+far_before_last_num+"15"+before_last_num+str(myList[i]['end'])+ending))
      

    def retranslateUii(self, ChartWindow):
        _translate = QtCore.QCoreApplication.translate
        ChartWindow.setWindowTitle(_translate("ChartWindow", "ChartWindow"))
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChartWindow = QtWidgets.QMainWindow()
    ui = Ui_ChartWindow()
    myList = [
            {
                'name': "P1:code",
                'start': 0,
                'end': 70
            },
            {
                'name': "hole1",
                'start': 70,
                'end': 150
            },
            {
                'name': "P2:Data",
                'start': 150,
                'end': 300
            },
            {
                'name': "Old Process1",
                'start': 300,
                'end': 600
            },
            {
                'name': "P2:Data",
                'start': 600,
                'end': 685
            },
            {
                'name': "P2:Data",
                'start': 600,
                'end': 685
            },
            {
                'name': "P2:Data",
                'start': 600,
                'end': 685
            }
        ]
    ui.setupUi(ChartWindow,myList)
    ChartWindow.show()
    sys.exit(app.exec_())
