# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'process.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(708, 717)
        Form.setStyleSheet("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 10, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.process_table = QtWidgets.QTableWidget(Form)
        self.process_table.setGeometry(QtCore.QRect(30, 90, 411, 331))
        self.process_table.setShowGrid(True)
        self.process_table.setRowCount(0)
        self.process_table.setObjectName("process_table")
        self.process_table.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.process_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.process_table.setHorizontalHeaderItem(1, item)
        self.process_table.horizontalHeader().setDefaultSectionSize(200)
        self.process_table.horizontalHeader().setHighlightSections(True)
        self.allocate_button = QtWidgets.QPushButton(Form)
        self.allocate_button.setGeometry(QtCore.QRect(200, 430, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.allocate_button.setFont(font)
        self.allocate_button.setStyleSheet("\n"
"background-color: rgb(6, 239, 33);\n"
"")
        self.allocate_button.setObjectName("allocate_button")
        self.memory_button = QtWidgets.QPushButton(Form)
        self.memory_button.setGeometry(QtCore.QRect(520, 620, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.memory_button.setFont(font)
        self.memory_button.setStyleSheet("")
        self.memory_button.setObjectName("memory_button")
        self.add_process_button = QtWidgets.QPushButton(Form)
        self.add_process_button.setGeometry(QtCore.QRect(370, 620, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_process_button.setFont(font)
        self.add_process_button.setStyleSheet("")
        self.add_process_button.setObjectName("add_process_button")
        self.deallocate_button = QtWidgets.QPushButton(Form)
        self.deallocate_button.setGeometry(QtCore.QRect(490, 260, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.deallocate_button.setFont(font)
        self.deallocate_button.setStyleSheet("")
        self.deallocate_button.setObjectName("deallocate_button")
        self.add_segment_button = QtWidgets.QPushButton(Form)
        self.add_segment_button.setGeometry(QtCore.QRect(30, 430, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_segment_button.setFont(font)
        self.add_segment_button.setObjectName("add_segment_button")
        self.number_of_segments = QtWidgets.QSpinBox(Form)
        self.number_of_segments.setGeometry(QtCore.QRect(200, 30, 71, 31))
        self.number_of_segments.setObjectName("number_of_segments")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "number of segments:"))
        item = self.process_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Segment name"))
        item = self.process_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Segment Size"))
        self.allocate_button.setText(_translate("Form", "Allocate this process"))
        self.memory_button.setText(_translate("Form", "Show Memory"))
        self.add_process_button.setText(_translate("Form", "Add new process"))
        self.deallocate_button.setText(_translate("Form", "Deallocate"))
        self.add_segment_button.setText(_translate("Form", "Add Segment"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
